"""update user table

Added : 
    auth_provider: Literal["password", "google"]
    is_currently_employed: bool                 # to account for past employees/users
    can_ingest: bool                            # will restrict use of ingest routes
    
Updated:
    hashed_password -> nullable                 # users using google login will have no password

Revision ID: 19451e5429a3
Revises: b9e007c417e1
Create Date: 2026-08-14 16:27:07.559159

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '19451e5429a3'
down_revision = 'b9e007c417e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('is_currently_employed', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('can_ingest', sa.Boolean(), nullable=False))
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'can_ingest')
    op.drop_column('user', 'is_currently_employed')
    op.drop_column('user', 'auth_provider')
    # ### end Alembic commands ###