"""added brand directory

Revision ID: 508e1f31e62e
Revises: 19451e5429a3
Create Date: 2026-08-14 18:10:58.182915

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '508e1f31e62e'
down_revision = '19451e5429a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gstin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("gstin = '' OR gstin ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$'", name='ck_brand_gstin_format'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gstin')
    )
    op.create_index(op.f('ix_brand_name'), 'brand', ['name'], unique=True)
    op.add_column('campaign', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_campaign_campaign_name'), 'campaign', ['campaign_name'], unique=False)
    op.create_foreign_key(None, 'campaign', 'brand', ['brand_id'], ['id'])
    op.drop_column('campaign', 'brand_name')
    op.alter_column('company', 'gstin',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.add_column('pitch', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_pitch_company_name'), table_name='pitch')
    op.create_index(op.f('ix_pitch_campaign_name'), 'pitch', ['campaign_name'], unique=False)
    op.drop_constraint(op.f('pitch_billing_company_id_fkey'), 'pitch', type_='foreignkey')
    op.create_foreign_key(None, 'pitch', 'brand', ['brand_id'], ['id'])
    op.drop_column('pitch', 'billing_company_id')
    op.drop_column('pitch', 'company_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('pitch', sa.Column('billing_company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.create_foreign_key(op.f('pitch_billing_company_id_fkey'), 'pitch', 'company', ['billing_company_id'], ['id'])
    op.drop_index(op.f('ix_pitch_campaign_name'), table_name='pitch')
    op.create_index(op.f('ix_pitch_company_name'), 'pitch', ['company_name'], unique=False)
    op.drop_column('pitch', 'brand_id')
    op.alter_column('company', 'gstin',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.add_column('campaign', sa.Column('brand_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.drop_index(op.f('ix_campaign_campaign_name'), table_name='campaign')
    op.drop_column('campaign', 'brand_id')
    op.drop_index(op.f('ix_brand_name'), table_name='brand')
    op.drop_table('brand')
    # ### end Alembic commands ###