"""add ingest_job table

Revision ID: 56cb9641a00c
Revises: 834f0b6728a8
Create Date: 2026-08-19 00:05:40.652858

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56cb9641a00c'
down_revision = '834f0b6728a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('received', sa.Integer(), nullable=False),
    sa.Column('inserted', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_job_job_id'), 'ingest_job', ['job_id'], unique=True)
    op.create_index(op.f('ix_ingest_job_source'), 'ingest_job', ['source'], unique=False)
    op.create_index(op.f('ix_ingest_job_status'), 'ingest_job', ['status'], unique=False)
    op.alter_column('brand', 'gstin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brand', 'gstin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_ingest_job_status'), table_name='ingest_job')
    op.drop_index(op.f('ix_ingest_job_source'), table_name='ingest_job')
    op.drop_index(op.f('ix_ingest_job_job_id'), table_name='ingest_job')
    op.drop_table('ingest_job')
    # ### end Alembic commands ###