"""add errors_truncated to ingest_job

Revision ID: 9536b3040da8
Revises: e78770692afa
Create Date: 2026-08-21 14:37:53.832994

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = "9536b3040da8"
down_revision = "e78770692afa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ingest_job",
        sa.Column("errors_truncated", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ingest_job", "errors_truncated")
    # ### end Alembic commands ###
