"""added trigram to brand_name

Revision ID: cf3e3feb4999
Revises: f4c6b8207dbf
Create Date: 2026-08-14 18:55:26.490604

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cf3e3feb4999'
down_revision = 'f4c6b8207dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brand_name'), table_name='brand')
    op.create_index('ix_brand_name_trgm', 'brand', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_unique_constraint(None, 'brand', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brand', type_='unique')
    op.drop_index('ix_brand_name_trgm', table_name='brand', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_brand_name'), 'brand', ['name'], unique=True)
    # ### end Alembic commands ###