"""Added display_name to Brand table

Revision ID: dae031bc730a
Revises: 56cb9641a00c
Create Date: 2026-08-19 12:00:58.212207

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dae031bc730a'
down_revision = '56cb9641a00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brand', 'display_name')
    # ### end Alembic commands ###