"""added trigram to creator

Revision ID: f4c6b8207dbf
Revises: 508e1f31e62e
Create Date: 2026-08-14 18:52:57.361997

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f4c6b8207dbf'
down_revision = '508e1f31e62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_creator_cats_trgm', 'creator', ['categories_raw'], unique=False, postgresql_using='gin', postgresql_ops={'categories_raw': 'gin_trgm_ops'})
    op.create_index('ix_creator_city_trgm', 'creator', ['city'], unique=False, postgresql_using='gin', postgresql_ops={'city': 'gin_trgm_ops'})
    op.create_index('ix_creator_langs_trgm', 'creator', ['languages_raw'], unique=False, postgresql_using='gin', postgresql_ops={'languages_raw': 'gin_trgm_ops'})
    op.create_index('ix_creator_name_trgm', 'creator', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_creator_username_trgm', 'creator', ['username'], unique=False, postgresql_using='gin', postgresql_ops={'username': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_creator_username_trgm', table_name='creator', postgresql_using='gin', postgresql_ops={'username': 'gin_trgm_ops'})
    op.drop_index('ix_creator_name_trgm', table_name='creator', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_creator_langs_trgm', table_name='creator', postgresql_using='gin', postgresql_ops={'languages_raw': 'gin_trgm_ops'})
    op.drop_index('ix_creator_city_trgm', table_name='creator', postgresql_using='gin', postgresql_ops={'city': 'gin_trgm_ops'})
    op.drop_index('ix_creator_cats_trgm', table_name='creator', postgresql_using='gin', postgresql_ops={'categories_raw': 'gin_trgm_ops'})
    # ### end Alembic commands ###